name: Il2CppInspectorRedux Build

on:
  push:
    branches: [master, refactored-versioning]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build GUI
        run: dotnet publish ./Il2CppInspector.GUI/Il2CppInspector.GUI.csproj --configuration Release --framework net9.0-windows --self-contained false

      - name: Build CLI
        run: dotnet publish ./Il2CppInspector.CLI/Il2CppInspector.CLI.csproj --configuration Release --framework net9.0 --self-contained false

      - name: Add Plugins folder (GUI)
        shell: pwsh
        working-directory: Il2CppInspector.GUI/bin/Release/net9.0-windows/win-x64/publish
        run: ../../../../../../get-plugins.ps1

      - name: Add Plugins folder (CLI)
        shell: pwsh
        working-directory: Il2CppInspector.CLI/bin/Release/net9.0/win-x64/publish
        run: ../../../../../../get-plugins.ps1

      - name: Upload GUI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Il2CppInspectorRedux.GUI
          path: Il2CppInspector.GUI/bin/Release/net9.0-windows/win-x64/publish

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Il2CppInspectorRedux.CLI
          path: Il2CppInspector.CLI/bin/Release/net9.0/win-x64/publish
